'use client';
import { useState, useEffect, type ReactNode } from 'react';
import book from '../content/textbook.json';
import images from '../content/image-sources.json';
import { glossary, sources } from '../content/reference';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
export type LessonBlock={type:string;text?:string;items?:string[];ordered?:boolean;rows?:string[][]};
export const lessonList=book.lessons;
function rich(s:string):ReactNode[]{return s.split(/(\*\*.*?\*\*)/g).map((x,i)=>x.startsWith('**')?<strong key={i}>{x.slice(2,-2)}</strong>:x);}
export function LessonBody({blocks}:{blocks:LessonBlock[]}){return <div className="textbook-body">{blocks.map((b,i)=>{
 if(b.type==='heading')return <h2 id={`section-${i}`} key={i}>{b.text}</h2>;
 if(b.type==='paragraph')return <p key={i}>{rich(b.text||'')}</p>;
 if(b.type==='answer')return <details className="answer-box" key={i}><summary>先回答，再揭晓参考答案</summary><p>{rich(b.text||'')}</p></details>;
 if(b.type==='list'){const Tag=b.ordered?'ol':'ul';return <Tag key={i}>{b.items?.map((x,j)=><li key={j}>{rich(x)}</li>)}</Tag>;}
 if(b.type==='table')return <div className="textbook-table" key={i}><table><thead><tr>{b.rows?.[0].map((x,j)=><th key={j}>{rich(x)}</th>)}</tr></thead><tbody>{b.rows?.slice(1).map((row,j)=><tr key={j}>{row.map((x,k)=><td key={k}>{rich(x)}</td>)}</tr>)}</tbody></table></div>;
 return null;
 })}</div>;}
export default function Academy({initialLesson=1,onStart,onLab,onLearning}:{initialLesson?:number;onStart:(id:number,title:string)=>void;onLab:()=>void;onLearning:()=>void}){
 const [id,setId]=useState(initialLesson);const [search,setSearch]=useState('');const [view,setView]=useState('lessons');const [indexOpen,setIndexOpen]=useState(false);const selected=book.lessons.find(l=>l.id===id)||book.lessons[0];
 useEffect(()=>{let closed:HTMLDetailsElement[]=[];const before=()=>{closed=Array.from(document.querySelectorAll<HTMLDetailsElement>('#academy-reading details:not([open])'));closed.forEach(d=>d.open=true);};const after=()=>{closed.forEach(d=>d.open=false);closed=[];};window.addEventListener('beforeprint',before);window.addEventListener('afterprint',after);return()=>{window.removeEventListener('beforeprint',before);window.removeEventListener('afterprint',after);};},[]);
 const filtered=book.lessons.filter(l=>!search||`${l.title} ${l.blocks.map(b=>b.text||b.items?.join(' ')||b.rows?.flat().join(' ')||'').join(' ')}`.includes(search));
 function choose(n:number){setId(n);setView('lessons');setIndexOpen(false);window.history.replaceState(null,'',`?lesson=${n}`);document.getElementById('academy-reading')?.scrollIntoView({block:'start'});}
 return <div className="academy"><div className="page-heading"><p className="eyebrow">完整教材 / 第二版 / 24 节课</p><h1>从观察，走到自己的作品。</h1><p>全部讲解、练习、自测与补练都在这里。每周一节核心课，余下时间反复实拍、选片与完善项目。</p><div className="button-row"><a className="small-button" href="/teaching/photography-textbook.html" download>下载完整离线教材</a><button className="small-button" onClick={onLab}>打开练习工具</button><button className="small-button" onClick={onLearning}>思维导图与闪卡</button></div></div>
 <Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList className="academy-subtabs"><TabsTrigger value="lessons">24节完整课</TabsTrigger><TabsTrigger value="examples">示例拆解</TabsTrigger><TabsTrigger value="reference">术语与查错</TabsTrigger></TabsList>
 <TabsContent value="lessons"><div className="mobile-course-actions"><button className="small-button" onClick={()=>document.getElementById('academy-reading')?.scrollIntoView({behavior:'smooth',block:'start'})}>继续阅读本课 ↓</button><button className="small-button" aria-expanded={indexOpen} onClick={()=>setIndexOpen(open=>!open)}>{indexOpen?'收起课程目录':'选择其他课程'}</button></div><div className="course-layout"><aside className={`textbook-index ${indexOpen?'is-open':''}`}><label className="field">搜索课程内容<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="例如：对焦、图注、打印"/></label><p className="muted">{filtered.length} 节匹配 · 旧练习档案保留在原模块</p><nav className="module-list" aria-label="完整课程目录">{filtered.map(l=><button key={l.id} className={l.id===id?'selected':''} onClick={()=>choose(l.id)}><span>{String(l.id).padStart(2,'0')}</span><div><strong>{l.title}</strong><small>第 {l.id} 周 · 核心课 60–90 分钟</small></div></button>)}</nav>{!filtered.length&&<p>没有找到这个词，试试更短的关键词。</p>}</aside><article id="academy-reading" className="paper-panel textbook-reading"><p className="eyebrow">第 {String(id).padStart(2,'0')} 课 · 模块 {selected.moduleId}</p><h1>{selected.title}</h1><p className="muted">完成顺序：理解 → 比较 → 实拍 → 选片 → 自查 → 重拍。先保留证据，再判断掌握。</p><div className="lesson-jump">{selected.blocks.map((b,i)=>b.type==='heading'?<a key={i} href={`#section-${i}`}>{b.text}</a>:null)}</div><LessonBody blocks={selected.blocks}/><div className="lesson-footer"><button className="action" onClick={()=>onStart(id,selected.title)}>记录本课作业 →</button><button className="small-button" onClick={onLab}>打开练习工具</button><button className="small-button" onClick={()=>window.print()}>打印本课</button></div><div className="section-heading">{id>1?<button className="small-button" onClick={()=>choose(id-1)}>← 上一课</button>:<span/>}{id<24?<button className="small-button" onClick={()=>choose(id+1)}>下一课 →</button>:<span>完成毕业项目后，用验收结果安排下一轮。</span>}</div></article></div></TabsContent>
 <TabsContent value="examples"><section className="paper-panel"><h2>先描述看到什么，再讨论它意味着什么。</h2><p>三张照片用于比较空间、关系与阅读方式。参数和人物心理无法仅凭照片确定；来源说明是事实核对依据，不是需要另学的课程。</p></section>{images.assets.map(a=><article className="paper-panel teaching-example" key={a.id}><figure><img src={a.path} alt={a.original_title} width={a.width} height={a.height} loading="lazy"/><figcaption>{a.author} · {a.date}</figcaption></figure><div><p className="eyebrow">{a.category}</p><h2>{a.original_title}</h2><h3>先自己观察</h3><p>第一眼落在哪里？哪两块形成关系？如果裁去一部分，意义会怎样改变？</p><details className="answer-box"><summary>查看客观观察与分析起点</summary><ul>{a.visible_elements.map(x=><li key={x}>{x}</li>)}</ul></details><h3>馆藏背景</h3><p>{a.background}</p>{'ethics_prompt' in a&&<p>{a.ethics_prompt}</p>}<p className="muted">{a.rights}</p><a href={a.source_url} target="_blank" rel="noreferrer">查看馆藏记录 ↗</a></div></article>)}</TabsContent>
 <TabsContent value="reference"><div className="work-grid"><section className="paper-panel"><h2>遇到问题，从这里回课</h2>{[[6,'照片不清楚：区分对焦、运动与手抖'],[5,'照片太亮或太暗：理解曝光与高光'],[4,'画面乱：检查边缘、亮部与遮挡'],[12,'组照没故事：检查顺序与信息'],[14,'颜色不统一：检查光源与白平衡'],[19,'照片很多但项目没进展：删减与缺口'],[22,'打印模糊或偏暗：检查尺寸与输出']].map(([n,t])=><button className="record-card" key={n} onClick={()=>choose(Number(n))}>{t} →</button>)}<h3>什么算学会</h3><p>做对自测＝理解开始形成；完成对照＝能控制一个变量；在新场景重复成功＝趋向稳定掌握。每课的验收表告诉你下一步补哪里。</p></section><section className="paper-panel"><h2>资料核对说明</h2><p>教材为原创讲解与练习设计。下列链接用于核对技术概念和来源，不是学习的前置任务。照片的馆藏来源与使用条件已在示例库说明。</p>{sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><br/>{s.use}</p>)}</section></div><section className="paper-panel"><h2>术语速查</h2><dl className="glossary">{glossary.map(([term,def])=><div key={term}><dt>{term}</dt><dd>{def}</dd></div>)}</dl></section></TabsContent>
 </Tabs></div>;
}
