'use client';
import { useEffect, useRef, useState } from 'react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Slider } from '@/components/ui/slider';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Progress } from '@/components/ui/progress';
import { terms,stages,scenarios } from '../content/learning-data';
import book from '../content/textbook.json';
import images from '../content/image-sources.json';
import { schedule,type LearningProgress,type Rating } from './learning-progress';
const empty:LearningProgress={cards:{},decisions:{}};
function Picker({value,change,label,items}:{value:string;change:(v:string)=>void;label:string;items:{value:string;label:string}[]}){return <Select value={value} onValueChange={v=>v!==null&&change(v)} items={items}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>;}
function StageFilter({value,change}:{value:string;change:(v:string)=>void}){return <Picker value={value} change={change} label="课程阶段" items={[{value:'all',label:'全部阶段'},...stages.map((s,i)=>({value:String(i),label:s.name}))]}/>;}
function CourseMap({openLesson}:{openLesson:(id:number)=>void}){
 const [expanded,setExpanded]=useState<number[]>([0,1,2,3,4,5]);const [selected,setSelected]=useState(1);const l=book.lessons[selected-1];
 return <><div className="map-root"><strong>个人摄影创作</strong><span>观看 → 控制 → 叙事 → 项目 → 呈现</span></div><div className="course-map">{stages.map((s,i)=><section className="map-branch" key={s.name}><button className="map-stage" aria-expanded={expanded.includes(i)} aria-controls={`branch-${i}`} onClick={()=>setExpanded(x=>x.includes(i)?x.filter(n=>n!==i):[...x,i])}><span>0{i+1} / 第{s.range[0]}–{s.range[1]}课</span><strong>{s.name}</strong><small>{s.goal} · {expanded.includes(i)?'收起':'展开'}</small></button><div id={`branch-${i}`} hidden={!expanded.includes(i)} className="map-leaves">{book.lessons.slice(s.range[0]-1,s.range[1]).map(c=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}><b>{String(c.id).padStart(2,'0')}</b>{c.title}</button>)}</div></section>)}</div><section className="paper-panel map-detail" aria-live="polite"><p className="eyebrow">当前节点 / 第{selected}课</p><h2>{l.title}</h2><p>{l.blocks.find(b=>b.type==='paragraph')?.text}</p><div className="concept-chips">{l.blocks.filter(b=>b.type==='heading'&&/^\d+\./.test(b.text||'')).map((b,i)=><span key={i}>{b.text?.replace(/^\d+\. /,'')}</span>)}</div><button className="action" onClick={()=>openLesson(selected)}>阅读这节课</button></section><p className="muted">连线表示课程组织和建议学习顺序，不表示已掌握。可先展开阶段，再选择课程节点。</p></>;
}
function TermTable({openLesson,study}:{openLesson:(id:number)=>void;study:(id:string)=>void}){
 const [search,setSearch]=useState('');const [stage,setStage]=useState('all');const filtered=terms.filter(t=>(stage==='all'||t.stage===Number(stage))&&`${t.term} ${t.definition} ${t.example} ${t.confusion}`.toLowerCase().includes(search.trim().toLowerCase()));
 return <><div className="study-toolbar"><label className="field">搜索术语、例子或疑问<input type="search" placeholder="例如：ISO、模糊、打印" value={search} onChange={e=>setSearch(e.target.value)}/></label><StageFilter value={stage} change={setStage}/><span>{filtered.length} / {terms.length} 个术语</span></div><div className="term-table" tabIndex={0} role="region" aria-label="摄影术语解释表"><table><thead><tr><th>术语 / 课程</th><th>解释与例子</th><th>容易混淆</th><th>复习</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><th scope="row">{t.term}<button className="term-link" onClick={()=>openLesson(t.lesson)}>第{t.lesson}课</button></th><td><p>{t.definition}</p><p className="term-example">例：{t.example}</p></td><td>{t.confusion}</td><td><button className="small-button" onClick={()=>study(t.id)}>练这张卡</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="empty-state">没有匹配的术语，试试更短的词或全部阶段。</p>}</>;
}
function Cards({progress,save,canSave,busy,focus,openLesson,maxLesson}:{progress:LearningProgress;save:(p:LearningProgress)=>Promise<boolean>;canSave:boolean;busy:boolean;focus:string|undefined;openLesson:(id:number)=>void;maxLesson?:number}){
 const [stage,setStage]=useState('all');const [mode,setMode]=useState('due');const [now,setNow]=useState(()=>Date.now());const [id,setId]=useState<string|undefined>(focus);const [flipped,setFlipped]=useState(false);const [draft,setDraft]=useState('');const [notice,setNotice]=useState('');const [guest,setGuest]=useState<LearningProgress>(empty);const lock=useRef(false);
 const p=canSave?progress:guest;
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 const pool=terms.filter(t=>(maxLesson===undefined||t.lesson<=maxLesson)&&(stage==='all'||t.stage===Number(stage))&&(mode==='all'||!p.cards[t.id]||p.cards[t.id].due<=now));
 const queue=[...pool].sort((a,b)=>(p.cards[a.id]?.due??Number.MAX_SAFE_INTEGER)-(p.cards[b.id]?.due??Number.MAX_SAFE_INTEGER));
 const card=(id?terms.find(t=>t.id===id&&(maxLesson===undefined||t.lesson<=maxLesson)):undefined)||queue[0];const scopedTerms=terms.filter(t=>maxLesson===undefined||t.lesson<=maxLesson);const due=scopedTerms.filter(t=>p.cards[t.id]&&p.cards[t.id].due<=now).length;const learned=scopedTerms.filter(t=>p.cards[t.id]).length;
 function reset(){setId(undefined);setFlipped(false);setDraft('');setNotice('');}
 async function rate(r:Rating){if(!card||lock.current||busy)return;lock.current=true;const updated=schedule(p.cards[card.id],r);const next={...p,cards:{...p.cards,[card.id]:updated}};try{if(canSave){if(!await save(next)){setNotice('未保存成功；当前答案保留，请处理顶部提示后重试。');return;}}else setGuest(next);const remainder=queue.filter(c=>c.id!==card.id);setId(remainder[0]?.id);setFlipped(false);setDraft('');setNow(Date.now());setNotice(`${canSave?'已保存':'本次试用已记录'}：${card.term}。${r==='again'?'10分钟后':`${updated.interval}天后`}复习。`);}finally{lock.current=false;}}
 return <><div className="study-toolbar"><StageFilter value={stage} change={v=>{setStage(v);reset();}}/><Picker value={mode} change={v=>{setMode(v);reset();}} label="复习范围" items={[{value:'due',label:'到期与新卡'},{value:'all',label:'随时练习全部卡'}]}/><span>当前范围：第1–{maxLesson??24}课 · 已练 {learned}/{scopedTerms.length} · 到期 {due}</span></div><Progress value={scopedTerms.length?learned/scopedTerms.length*100:0} aria-label="已练习术语比例"/><p className="muted">{canSave?'评分后保存并安排下次复习。':'当前可试练；登录并载入档案后才能跨设备保存。'} 复习默认跟随当前学习周，答错后请回到对应课程完成实拍验证。</p>{card?<section className="flashcard" key={card.id}><p className="eyebrow">先回忆，再翻面 / 第{card.lesson}课</p><h2>{card.term}</h2><p>用自己的话解释，并举一个拍摄或编辑时的例子。</p><label className="field">我的回忆（可选草稿，不保存）<textarea rows={3} maxLength={2000} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="先写一句，再核对答案…"/></label>{!flipped?<button className="action" onClick={()=>setFlipped(true)}>翻面 · 核对解释</button>:<><div className="flash-answer"><h3>准确解释</h3><p>{card.definition}</p><h3>应用例子</h3><p>{card.example}</p><h3>辨析</h3><p>{card.confusion}</p></div><div className="button-row"><button disabled={busy} className="small-button" onClick={()=>void rate('again')}>没想起来 · 10分钟</button><button disabled={busy} className="small-button" onClick={()=>void rate('hard')}>不太稳 · 1天</button><button disabled={busy} className="action" onClick={()=>void rate('good')}>能解释 · {schedule(p.cards[card.id],'good',now).interval}天</button></div><button className="term-link" onClick={()=>openLesson(card.lesson)}>回到第{card.lesson}课理解</button></>}</section>:<section className="paper-panel"><h2>这个范围暂时没有待复习的卡。</h2><p>可以换一个阶段，或选择“随时练习全部卡”。遗忘卡约10分钟后重新出现。</p></section>}<p role="status" aria-live="polite">{notice}</p><p className="muted">规则：没想起来10分钟，不太稳1天；能解释依次3、7、15、30天（之后最多30天）。可随时提前练习，评分会重新计算复习时间。</p></>;
}
function Decisions({progress,save,canSave,busy,openLesson}:{progress:LearningProgress;save:(p:LearningProgress)=>Promise<boolean>;canSave:boolean;busy:boolean;openLesson:(id:number)=>void}){
 const [index,setIndex]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [revealed,setRevealed]=useState(false);const [recorded,setRecorded]=useState(false);const [notice,setNotice]=useState('');const q=scenarios[index];const lock=useRef(false);
 function select(n:number){setIndex(n);setChoice(null);setRevealed(false);setRecorded(false);setNotice('');}
 async function record(){if(choice===null||lock.current||recorded)return;lock.current=true;const old=progress.decisions[q.id]||{attempts:0,correct:0};const next={...progress,decisions:{...progress.decisions,[q.id]:{attempts:Math.min(10000,old.attempts+1),correct:Math.min(10000,old.correct+(choice===q.answer?1:0))}}};try{if(await save(next)){setRecorded(true);setNotice('已保存本次结果。请用实拍验证理解。');}else setNotice('保存失败，仍可重试。');}finally{lock.current=false;}}
 return <div className="decision-layout"><nav className="decision-index" aria-label="现场决策题">{scenarios.map((s,i)=><button key={s.id} aria-pressed={index===i} onClick={()=>select(i)}><span>{i+1}. 第{s.lesson}课</span><strong>{s.prompt}</strong><small>{progress.decisions[s.id]?`已练${progress.decisions[s.id].attempts}次 · 答对${progress.decisions[s.id].correct}次`:'尚无保存记录'}</small></button>)}</nav><section className="paper-panel"><p className="eyebrow">情境 {index+1} / {scenarios.length}</p><h2>{q.prompt}</h2><RadioGroup className="decision-options" aria-label="先做选择" disabled={revealed} value={choice===null?'':String(choice)} onValueChange={v=>setChoice(Number(v))}>{q.options.map((o,i)=><label key={o} htmlFor={`${q.id}-${i}`}><RadioGroupItem id={`${q.id}-${i}`} value={String(i)}/><span>{o}</span></label>)}</RadioGroup>{!revealed?<button className="action" disabled={choice===null} onClick={()=>setRevealed(true)}>查看原因与实拍任务</button>:<div className="decision-feedback" role="status"><h3>{choice===q.answer?'判断正确':'再看一次关键线索'}</h3><p>{q.why}</p><h3>带到现场验证</h3><p>{q.task}</p><div className="button-row"><button className="small-button" onClick={()=>openLesson(q.lesson)}>回第{q.lesson}课</button><button className="action" disabled={!canSave||busy||recorded} onClick={()=>void record()}>{recorded?'结果已保存':'保存本次结果'}</button><button className="small-button" onClick={()=>select((index+1)%scenarios.length)}>下一题</button></div>{!canSave&&<p className="muted">登录并载入档案后可保存结果。</p>}</div>}<p aria-live="polite">{notice}</p></section></div>;
}
function Framing({openLesson}:{openLesson:(id:number)=>void}){
 const [asset,setAsset]=useState(images.assets[0].id);const [grid,setGrid]=useState('thirds');const [x,setX]=useState(50);const [y,setY]=useState(50);const [revealed,setRevealed]=useState(false);const a=images.assets.find(a=>a.id===asset)!;
 return <><div className="study-toolbar"><Picker value={asset} label="示例照片" items={images.assets.map(a=>({value:a.id,label:a.original_title}))} change={v=>{setAsset(v);setX(50);setY(50);setRevealed(false);}}/><Picker value={grid} label="辅助线" items={[{value:'thirds',label:'三分线'},{value:'center',label:'中心线'},{value:'none',label:'不显示辅助线'}]} change={setGrid}/></div><div className="work-grid"><section className="paper-panel"><p>移动标记到你的第一眼落点，再检查它与线条、亮部和边缘的关系。</p><div className="framing-image"><img src={a.path} alt={a.original_title}/><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{grid==='thirds'&&<path d="M33.33 0V100 M66.67 0V100 M0 33.33H100 M0 66.67H100"/>}{grid==='center'&&<path d="M50 0V100 M0 50H100"/>}</svg><span className="attention-marker" style={{left:`${x}%`,top:`${y}%`}} aria-hidden="true"/></div><p className="muted">{a.author} · {a.date} · <a href={a.source_url} target="_blank" rel="noreferrer">馆藏来源</a></p><div className="lab-range"><label>注意力标记：横向 {x}%</label><Slider aria-label="注意力标记横向位置" value={[x]} min={0} max={100} step={1} onValueChange={v=>setX(Array.isArray(v)?v[0]:v)}/></div><div className="lab-range"><label>注意力标记：纵向 {y}%</label><Slider aria-label="注意力标记纵向位置" value={[y]} min={0} max={100} step={1} onValueChange={v=>setY(Array.isArray(v)?v[0]:v)}/></div></section><section className="paper-panel"><h2>观察任务</h2><ol><li>先关闭辅助线，找出最先吸引你的地方。</li><li>打开三分线，比较注意力落点与交点。是否一致？为什么？</li><li>切换中心线，描述左右重量，而不是数物体数量。</li><li>检查四边：哪些元素被截断？这些取舍是否帮助表达？</li></ol><p>辅助线用于提问，不给照片打分；主体不在交点也可能成立。标记是你的主观观察，不是自动识别结果。</p><button className="action" onClick={()=>setRevealed(!revealed)} aria-expanded={revealed}>{revealed?'收起':'对照'}可见元素</button>{revealed&&<ul>{a.visible_elements.map(t=><li key={t}>{t}</li>)}</ul>}<button className="term-link" onClick={()=>openLesson(4)}>回第4课：边框与层次</button><p className="muted">位置标记仅供本次观察，不保存。要留下比较结论，可写入练习档案。</p></section></div></>;
}
export default function LearningHub({progress,save,canSave,busy,openLesson,maxLesson}:{progress?:LearningProgress;save:(p:LearningProgress)=>Promise<boolean>;canSave:boolean;busy:boolean;openLesson:(id:number)=>void;maxLesson?:number}){
 const [view,setView]=useState('map');const [focus,setFocus]=useState<string>();const p=progress||empty;
 return <section className="learning-hub"><div className="study-heading"><h1>学习辅助</h1><p>先看知识之间的关系，再用回忆、判断与观察检验理解。</p></div><Tabs value={view} onValueChange={v=>{setView(String(v));setFocus(undefined);}}><TabsList className="lab-tabs"><TabsTrigger value="map">课程思维导图</TabsTrigger><TabsTrigger value="terms">术语解释表</TabsTrigger><TabsTrigger value="cards">闪卡复习</TabsTrigger><TabsTrigger value="decisions">现场决策训练</TabsTrigger><TabsTrigger value="framing">构图观察台</TabsTrigger></TabsList><TabsContent value="map"><CourseMap openLesson={openLesson}/></TabsContent><TabsContent value="terms"><TermTable openLesson={openLesson} study={id=>{setFocus(id);setView('cards');}}/></TabsContent><TabsContent value="cards"><Cards key={focus||'deck'} progress={p} save={save} canSave={canSave} busy={busy} focus={focus} openLesson={openLesson} maxLesson={maxLesson}/></TabsContent><TabsContent value="decisions"><Decisions progress={p} save={save} canSave={canSave} busy={busy} openLesson={openLesson}/></TabsContent><TabsContent value="framing"><Framing openLesson={openLesson}/></TabsContent></Tabs></section>;
}
