'use client';
import { useState,useRef,useEffect,useId } from 'react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Toggle } from '@/components/ui/toggle';
import { Slider } from '@/components/ui/slider';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { relativeEV,printCm,cropRect,adjustPixels,type Edits } from './photo-math';
function Range({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void}){const id=useId();return <div className="lab-range"><label id={id}>{label}<output>{Number(value.toFixed(2))}</output></label><Slider aria-labelledby={id} min={min} max={max} step={step} value={[value]} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>;}
function Pick({label,value,items,onChange}:{label:string;value:string;items:[string,string][];onChange:(s:string)=>void}){return <label className="field">{label}<Select value={value} onValueChange={v=>{if(v!==null)onChange(v);}} items={items.map(([value,label])=>({value,label}))}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>;}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadCanvas(canvas:HTMLCanvasElement,name:string){canvas.toBlob(b=>{if(b)download(b,name);},'image/jpeg',.93);}
async function decode(source:File|string,max=2400){
 if(source instanceof File && (!['image/jpeg','image/png','image/webp'].includes(source.type)||source.size>20*1024*1024))throw new Error('请选择不超过20MB的 JPEG、PNG 或 WebP；RAW / HEIC 请先生成兼容副本。');
 const url=typeof source==='string'?source:URL.createObjectURL(source);const image=new Image();
 try{await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('图片无法读取，请换一个兼容文件。'));image.src=url;});
 if(image.naturalWidth*image.naturalHeight>80000000)throw new Error('图片超过8000万像素，请选择较小的学习副本。');
 const scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext('2d');if(!context)throw new Error('此浏览器无法创建图像画布。');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);return {canvas,originalWidth:image.naturalWidth,originalHeight:image.naturalHeight};
 }finally{if(typeof source!=='string')URL.revokeObjectURL(url);}
}
function ExposureLab(){const [a,setA]=useState('4');const [s,setS]=useState('0.008');const [iso,setIso]=useState('400');const ev=relativeEV(Number(a),Number(s),Number(iso));return <div className="work-grid"><section className="paper-panel"><h2>保持亮度，改变画面表现</h2><p>基准：f/4 · 1/125秒 · ISO400。尝试缩短快门，再用其他参数补偿。</p><Pick label="光圈" value={a} onChange={setA} items={['2','2.8','4','5.6','8','11','16'].map(x=>[x,'f/'+x])}/><Pick label="快门时间" value={s} onChange={setS} items={[[1/30,'1/30秒'],[1/60,'1/60秒'],[1/125,'1/125秒'],[1/250,'1/250秒'],[1/500,'1/500秒'],[1/1000,'1/1000秒']].map(([v,l])=>[String(v),String(l)])}/><Pick label="ISO" value={iso} onChange={setIso} items={['100','200','400','800','1600','3200','6400'].map(x=>[x,x])}/><button className="small-button" onClick={()=>{setA('4');setS('0.008');setIso('400');}}>回到基准</button></section><section className="focus-panel"><p className="eyebrow">理想化亮度关系 / 不是照片模拟</p><h2>{ev>=0?'+':''}{ev.toFixed(2)} EV</h2><p>相对基准约 {Math.pow(2,ev).toFixed(2)} 倍输出亮度。</p><p>{Math.abs(ev)<.08?'亮度近似相同；景深、运动模糊与噪声仍可能不同。':ev>0?'结果趋向更亮。检查是否需要减少进光或调整 ISO。':'结果趋向更暗。先决定是否保留当前快门和景深，再补偿。'}</p><p>f/2.8、f/5.6 等是近似标示值，结果可能略偏离整挡。真实相机还受镜头透光、处理和动态范围影响。</p><p>练习：把快门设成1/500，找两种保持近似亮度的方案，再解释各自代价。</p></section></div>;}
const initial:Edits={exposure:0,contrast:0,shadows:0,highlights:0,warmth:0,tint:0,saturation:100};
function PhotoEditor(){const [source,setSource]=useState<HTMLCanvasElement|null>(null);const [name,setName]=useState('study');const [edits,setEdits]=useState(initial);const [ratio,setRatio]=useState('original');const [zoom,setZoom]=useState(1);const [x,setX]=useState(50);const [y,setY]=useState(50);const [showOriginal,setShowOriginal]=useState(false);const [message,setMessage]=useState('选择自己的照片，或载入站内示例。');const [busy,setBusy]=useState(false);const [hist,setHist]=useState<{histogram:number[];black:number;white:number;total:number}|null>(null);const canvas=useRef<HTMLCanvasElement>(null);const loadId=useRef(0);
 async function load(file:File|string){const request=++loadId.current;setBusy(true);try{const r=await decode(file);if(request!==loadId.current)return;setSource(r.canvas);setName(typeof file==='string'?'馆藏示例':file.name.replace(/\.[^.]+$/,''));setEdits({...initial});setRatio('original');setZoom(1);setX(50);setY(50);setShowOriginal(false);setMessage(`原图 ${r.originalWidth}×${r.originalHeight}；学习副本 ${r.canvas.width}×${r.canvas.height}。所有处理只在当前浏览器。`);}catch(e){if(request===loadId.current)setMessage((e as Error).message);}finally{if(request===loadId.current)setBusy(false);}}
 useEffect(()=>{if(!source||!canvas.current)return;const target=canvas.current;const r=cropRect(source.width,source.height,ratio==='original'?null:Number(ratio),zoom,x,y);target.width=Math.max(1,Math.round(r.width));target.height=Math.max(1,Math.round(r.height));const ctx=target.getContext('2d',{willReadFrequently:true});if(!ctx)return;ctx.drawImage(source,r.x,r.y,r.width,r.height,0,0,target.width,target.height);const pixels=ctx.getImageData(0,0,target.width,target.height);setHist(adjustPixels(pixels.data,showOriginal?initial:edits));ctx.putImageData(pixels,0,0);},[source,edits,ratio,zoom,x,y,showOriginal]);
 const update=(k:keyof Edits,v:number)=>setEdits(e=>({...e,[k]:v}));
 return <div className="editor-layout"><section className="paper-panel"><h2>照片调整</h2><label className="field">选择 JPEG / PNG / WebP<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.target.value='';}}/></label><button className="small-button" disabled={busy} onClick={()=>void load('/teaching/tetons-snake-river.jpg')}>载入风景示例</button><p className="muted" role="status">{message}</p><Pick label="裁切比例" value={ratio} onChange={setRatio} items={[['original','原比例'],['1','1:1'],['1.5','3:2'],['0.6666666667','2:3'],['1.3333333333','4:3'],['1.7777777778','16:9']]}/><Range label="裁切放大" value={zoom} min={1} max={3} step={.05} onChange={setZoom}/><Range label="水平位置" value={x} min={0} max={100} onChange={setX}/><Range label="垂直位置" value={y} min={0} max={100} onChange={setY}/><Range label="曝光 EV" value={edits.exposure} min={-2} max={2} step={.1} onChange={v=>update('exposure',v)}/>{([['contrast','对比'],['highlights','高光'],['shadows','阴影'],['warmth','冷暖'],['tint','绿 / 洋红色偏']] as [keyof Edits,string][]).map(([key,label])=><Range key={key} label={label} value={edits[key]} min={-100} max={100} onChange={v=>update(key,v)}/>)}<Range label="饱和度（0为黑白）" value={edits.saturation} min={0} max={180} onChange={v=>update('saturation',v)}/><button className="small-button" onClick={()=>{setEdits({...initial});setZoom(1);setX(50);setY(50);setRatio('original');setShowOriginal(false);}}>重置全部调整</button></section><section className="paper-panel editor-preview"><h2>{source?'看见每一次调整的代价':'从一张自己的照片开始'}</h2><p>长边最高2400像素的学习副本；不会覆盖原片。没有RAW解码、内容去除、局部遮罩或专业软打样。</p><div className="canvas-stage"><canvas ref={canvas} aria-label="当前裁切与明暗色彩调整结果" hidden={!source}/>{!source&&<div className="empty-state">载入照片后，在左侧按“裁切 → 明暗 → 色彩”的顺序练习。</div>}</div>{hist&&<><div className="histogram" role="img" aria-label="当前处理后图像亮度直方图，左暗右亮">{hist.histogram.map((n,i)=><i key={i} style={{height:Math.max(1,n/Math.max(...hist.histogram)*100)+'%'}}/>)}</div><p className="muted">亮度剪切参考：黑端 {(hist.black/hist.total*100).toFixed(1)}% · 白端 {(hist.white/hist.total*100).toFixed(1)}%。不等于 RAW 余量；RGB单通道剪切可能未显示。</p></>}<div className="button-row"><button className="small-button" disabled={!source} aria-pressed={showOriginal} onClick={()=>setShowOriginal(!showOriginal)}>{showOriginal?'返回调整结果':'看调整前（保留裁切）'}</button><button className="action" disabled={!source||showOriginal} onClick={()=>{if(canvas.current)downloadCanvas(canvas.current,`${name}_study.jpg`);}}>下载调整后的 JPEG</button><button className="small-button" disabled={!source} onClick={()=>download(new Blob([JSON.stringify({source:name,edits,crop:{ratio,zoom,x,y},output:{width:canvas.current?.width,height:canvas.current?.height},note:'浏览器学习参数；不是相机拍摄参数。'},null,2)],{type:'application/json'}),`${name}_edits.json`)}>下载参数笔记</button></div><p className="muted">离开此工具会清空未下载图片与调整。先下载成品与参数，再在练习档案记录文件位置。馆藏示例不得改署成自己的作品。</p></section></div>;
}
type SheetImage={id:string;data:string;name:string;caption:string;selected:boolean;width:number;height:number};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
function SequenceLab(){const [photos,setPhotos]=useState<SheetImage[]>([]);const [title,setTitle]=useState('我的摄影项目');const [statement,setStatement]=useState('');const [message,setMessage]=useState('一次可加入最多40张图片，使用720像素学习副本。');const [busy,setBusy]=useState(false);
 async function add(files:FileList|null){if(!files)return;setBusy(true);const additions:SheetImage[]=[];let errors=0;try{for(const file of Array.from(files).slice(0,40-photos.length)){try{const r=await decode(file,720);additions.push({id:crypto.randomUUID(),data:r.canvas.toDataURL('image/jpeg',.88),name:file.name,caption:'',selected:true,width:r.canvas.width,height:r.canvas.height});}catch{errors++;}}setPhotos(p=>[...p,...additions]);setMessage(`新增${additions.length}张${errors?`，${errors}张无法读取`:''}。${files.length>40-photos.length?'超出40张的部分未加入。':''}请下载成果后再离开。`);}finally{setBusy(false);}}
 function move(i:number,delta:number){setPhotos(p=>{const next=[...p];[next[i],next[i+delta]]=[next[i+delta],next[i]];return next;});}
 const selected=photos.filter(p=>p.selected);
 async function sheet(){if(!selected.length)return;setBusy(true);try{const cols=Math.min(4,selected.length),w=360,h=310,c=document.createElement('canvas');c.width=cols*w;c.height=Math.ceil(selected.length/cols)*h+80;const ctx=c.getContext('2d');if(!ctx)throw new Error('画布不可用');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#172c23';ctx.font='bold 26px sans-serif';ctx.fillText(title.slice(0,35),20,45);for(let i=0;i<selected.length;i++){const p=selected[i];const image=new Image();await new Promise<void>((res,rej)=>{image.onload=()=>res();image.onerror=()=>rej(new Error('图片未能绘制'));image.src=p.data;});const scale=Math.min((w-30)/p.width,230/p.height),x=i%cols*w,y=Math.floor(i/cols)*h+80;ctx.drawImage(image,x+(w-p.width*scale)/2,y,p.width*scale,p.height*scale);ctx.fillStyle='#172c23';ctx.font='16px sans-serif';ctx.fillText(`${i+1}. ${p.name.slice(0,27)}`,x+15,y+252);ctx.font='14px sans-serif';ctx.fillText(p.caption.slice(0,22),x+15,y+278);}downloadCanvas(c,'摄影接触表.jpg');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function book(){const text=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font:18px/1.7 system-ui;margin:0;background:#eee;color:#172c23}.page{background:white;max-width:900px;min-height:65vh;padding:40px;margin:30px auto;box-sizing:border-box;break-after:page}img{display:block;max-width:100%;max-height:65vh;margin:auto;object-fit:contain}p{white-space:pre-wrap}small{font-size:14px}@media print{@page{margin:15mm}.page{margin:0;max-width:none;min-height:0;padding:0}body{background:white}img{max-height:75vh}small{color:#555}}</style><section class="page"><h1>${escape(title)}</h1><p>${escape(statement)}</p><small>阅读样稿；图像为学习副本，非印厂拼版文件。使用浏览器打印可保存PDF。</small></section>${selected.map((p,i)=>`<section class="page"><img alt="${escape(p.caption||p.name)}" src="${p.data}"><p>${escape(p.caption)}</p><small>${i+1} / ${selected.length} · ${escape(p.name)}</small></section>`).join('')}</html>`;download(new Blob([text],{type:'text/html;charset=utf-8'}),'摄影集阅读样稿.html');}
 return <><section className="paper-panel"><h2>选片与编排</h2><p>载入自己的照片，比较、暂留、改变顺序并填写图注。所有图片留在当前浏览器；未下载的编排在离开后会清空。</p><label className="field">选择多张照片<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy||photos.length>=40} onChange={e=>{void add(e.target.files);e.target.value='';}}/></label><p role="status">{busy?'正在处理图片…':message}</p><div className="form-row"><label className="field">项目 / 摄影集名称<input value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/></label><label className="field">创作说明<textarea rows={3} value={statement} maxLength={4000} onChange={e=>setStatement(e.target.value)}/></label></div><div className="button-row"><button className="action" disabled={busy||!selected.length} onClick={()=>void sheet()}>下载接触表（{selected.length}张）</button><button className="action secondary" disabled={busy||!selected.length} onClick={book}>下载阅读样稿 HTML</button><button className="small-button" disabled={!photos.length} onClick={()=>download(new Blob([JSON.stringify({title,statement,sequence:photos.map(({data,...p})=>p)},null,2)],{type:'application/json'}),'作品顺序与图注.json')}>下载顺序与图注</button></div><p className="muted">暂不选不会删除图片。导出只使用“暂留”照片，编号按当前顺序。样稿图像最高720像素，适合阅读与排版判断，不是高质量印刷母版。</p></section><div className="contact-grid">{photos.map((p,i)=><article className={`paper-panel contact-item ${p.selected?'':'unselected'}`} key={p.id}><img src={p.data} width={p.width} height={p.height} alt={p.name}/><h3>{i+1}. {p.name}</h3><Toggle className="small-button" pressed={p.selected} onPressedChange={pressed=>setPhotos(all=>all.map(a=>a.id===p.id?{...a,selected:pressed}:a))}>{p.selected?'暂留 ✓':'暂不选'}</Toggle><div className="button-row"><button className="small-button" disabled={i===0} onClick={()=>move(i,-1)}>← 前移</button><button className="small-button" disabled={i===photos.length-1} onClick={()=>move(i,1)}>后移 →</button></div><label className="field">作用 / 图注<textarea value={p.caption} rows={3} maxLength={500} onChange={e=>setPhotos(all=>all.map(a=>a.id===p.id?{...a,caption:e.target.value}:a))}/></label></article>)}</div>{!photos.length&&<div className="paper-panel empty-state">先载入第1课的9–15张候选，尝试选3张并说明理由。</div>}</>;
}
function PrintLab(){const [width,setWidth]=useState(3000);const [height,setHeight]=useState(2000);const [ppi,setPpi]=useState(300);return <div className="work-grid"><section className="paper-panel"><h2>打印尺寸计算</h2><p>输入导出文件的真实像素尺寸。只改变PPI标签不会增加细节。</p>{([['宽度像素',width,setWidth],['高度像素',height,setHeight],['目标 PPI',ppi,setPpi]] as const).map(([label,value,set])=><label key={label} className="field">{label}<input type="number" min="1" max={label==='目标 PPI'?1200:100000} value={value} onChange={e=>set(Math.min(label==='目标 PPI'?1200:100000,Math.max(1,Number(e.target.value)||1)))}/></label>)}</section><section className="focus-panel"><p className="eyebrow">在 {ppi} PPI 下</p><h2>{printCm(width,ppi).toFixed(1)} × {printCm(height,ppi).toFixed(1)} 厘米</h2><p>公式：像素 ÷ PPI × 2.54。</p><p>这是几何换算，不保证实际清晰度或颜色。裁切、噪声、对焦、纸张、观看距离都会影响效果，正式输出前做样张。</p><p>练习：2400像素宽按300PPI输出，结果应约20.3厘米。尝试改为240PPI，比较尺寸而非宣称细节增加。</p></section></div>;}
export default function PracticeLab(){return <section><div className="page-heading"><p className="eyebrow">理解 → 动手 → 对照</p><h1>把讲解变成可以验证的选择。</h1><p>这些工具用于学习与样稿。图片在当前浏览器处理，不上传、不自动保存到学习档案；完成后下载成果并记录位置。</p></div><Tabs defaultValue="exposure"><TabsList className="lab-tabs"><TabsTrigger value="exposure">曝光关系</TabsTrigger><TabsTrigger value="edit">照片调整</TabsTrigger><TabsTrigger value="sequence">选片与编排</TabsTrigger><TabsTrigger value="print">打印尺寸</TabsTrigger></TabsList><TabsContent value="exposure"><ExposureLab/></TabsContent><TabsContent value="edit"><PhotoEditor/></TabsContent><TabsContent value="sequence"><SequenceLab/></TabsContent><TabsContent value="print"><PrintLab/></TabsContent></Tabs></section>;}
