import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { importedState, mergeStudy, canonical } from '../app/sync-data.ts';
import { emptyState } from '../app/state.ts';
const practice = { id:'same',module:1,date:'2026-09-15',hours:1,title:'练习',intention:'',evidence:'',reflection:'',feedback:'',next:'',status:'待点评' };
const remote = {...emptyState,week:3,records:[practice]};
const incoming = {...emptyState,week:7,records:[{...practice,reflection:'不同设备的文字'}]};
let nextId = 0;
const merged = mergeStudy(remote,incoming,1,()=>`new-${++nextId}`);
assert.equal(merged.week,3); assert.equal(merged.records.length,2); assert.equal(merged.records[0].reflection,'');
assert.equal(mergeStudy(merged,incoming,2).records.length,2,'reimport must not duplicate a conflict copy');
assert.equal(mergeStudy(remote,emptyState,1).records.length,1,'empty incoming must not erase remote');
assert.deepEqual(mergeStudy(emptyState,incoming,0),incoming);
assert.throws(()=>importedState({state:{week:99}}));
assert.equal(canonical({a:1,b:2}),canonical({b:2,a:1}));

const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;
insert into auth.users values ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');`);
await db.exec(await readFile(new URL('../supabase/migrations/202609150001_study_sync.sql',import.meta.url),'utf8'));
await db.exec('set role authenticated');
const asUser = id => db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);
const save = (state,revision) => db.query('select * from public.save_study_state($1::jsonb,$2::bigint)',[JSON.stringify(state),revision]);
await asUser('00000000-0000-0000-0000-000000000001');
assert.equal((await save(remote,0)).rows[0].revision,1);
assert.equal((await db.query('select * from study_states')).rows.length,1);
await assert.rejects(save(incoming,0),e=>e.code==='40001');
assert.equal((await save(merged,1)).rows[0].revision,2);
await assert.rejects(save(incoming,1),e=>e.code==='40001');
await assert.rejects(db.query("update study_states set data='{}'"),e=>e.code==='42501');
await assert.rejects(save({...emptyState,week:99},2),e=>e.code==='22023');
await asUser('00000000-0000-0000-0000-000000000002');
assert.equal((await db.query('select * from study_states')).rows.length,0,'user B cannot read user A');
assert.equal((await save(emptyState,0)).rows[0].revision,1);
await asUser('00000000-0000-0000-0000-000000000001');
assert.deepEqual((await db.query('select data from study_states')).rows[0].data,merged,'user B cannot overwrite user A');
await asUser(''); await assert.rejects(save(emptyState,0),e=>e.code==='42501');
await db.exec('reset role; set role anon');
await assert.rejects(db.query('select * from study_states'),e=>e.code==='42501');
await assert.rejects(save(emptyState,0),e=>e.code==='42501');
await db.close();
console.log('PASS: migration merge, repeat import, JSONB ordering, SQL RLS isolation, anonymous denial, atomic version conflicts.');
